

name: python script

on:
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"
    - cron: "20 1,5,9,13,17,21 * * *"
    - cron: "40 2,6,10,14,18,22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: refactor python
        run: |
          TIMESTAMP_FILE="updates.txt"
          echo "Last checked: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > "$TIMESTAMP_FILE"
          git config user.name "peters bot"
          git config user.email "spicezke@gmail.com"
          git add "$TIMESTAMP_FILE"
          if ! git diff --cached --quiet; then
            git commit -m "Update timestamp: $(date -u)"
          fi
      - name: Push changes
        run: git push origin HEAD
